# .github/workflows/metrics.yml
name: GitHub Metrics
on:
  # يعمل يومياً في منتصف الليل
  schedule: [{cron: "0 0 * * *"}]
  # يمكن تشغيله يدوياً  
  workflow_dispatch:
  # يعمل عند push للـ main branch
  push: {branches: ["master", "main"]}
  
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          # بيانات أساسية
          user: ali90h
          template: classic
          base: header, activity, community, repositories, metadata
          
          # الإعدادات العامة
          config_timezone: Asia/Baghdad
          config_order: base.header, base.activity+community, base.repositories
          
          # إعدادات اللغات مع الألوان والتفاصيل
          plugin_languages: yes
          plugin_languages_sections: most-used, recently-used
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_threshold: 0%
          
          # إحصائيات النشاط المتقدمة
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_visibility: all
          plugin_activity_timestamps: yes
          
          # معلومات المجتمع
          plugin_people: yes
          plugin_people_limit: 24
          plugin_people_size: 28
          plugin_people_types: followers, following
          
          # إحصائيات الـ Issues والـ PRs (محسنة)
          plugin_followup: yes
          plugin_followup_sections: repositories, user
          plugin_followup_indepth: yes
          
          # إضافة plugin للـ contributions الخارجية
          plugin_contributions: yes
          plugin_contributions_display: detailed
          plugin_contributions_sections: contributions
          
          # خريطة النشاط ثلاثية الأبعاد (حجم صغير مثل Byron)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_isocalendar_compact: yes
          
          # Achievements والجوائز (بدون الأخطاء)
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_display: compact
          plugin_achievements_limit: 10
          
          # خطوط الكود المكتوبة
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          
          # المشاريع البارزة
          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_repositories: yes
          
          # Traffic وإحصائيات الزوار
          plugin_traffic: yes
          
          # إعدادات المظهر النهائية
          config_display: large
          config_animations: yes
          
  # وظيفة منفصلة للـ detailed metrics (بدون الأقسام غير المرغوبة)
  detailed-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.detailed.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: ali90h
          template: classic
          base: header, activity, repositories
          
          # كل التفاصيل المتقدمة
          config_timezone: Asia/Baghdad
          config_order: languages, followup, people, lines, traffic
          config_display: large
          config_animations: yes
          
          # اللغات بشكل مفصل
          plugin_languages: yes
          plugin_languages_sections: most-used, recently-used
          plugin_languages_colors: github
          plugin_languages_limit: 12
          plugin_languages_details: bytes-size, percentage, lines
          plugin_languages_threshold: 1%
          plugin_languages_analysis_timeout: 15
          
          # الخريطة ثلاثية الأبعاد (حجم مضغوط مثل Byron)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_isocalendar_compact: yes
          
          # الإحصائيات بدون stargazers والأقسام غير المرغوبة
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: classic
          
          # تعطيل stargazers و recent activity غير المرغوب فيها
          plugin_stargazers: no
          plugin_recent_activity: no
          
  # المساهمات الخارجية (محسنة ومركزة)
  external-contributions:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: external-contributions.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: ali90h
          template: classic
          base: ""
          
          # إعدادات للمساهمات الخارجية
          config_timezone: Asia/Baghdad
          config_display: large
          
          # plugin للـ Pull Requests المرسلة للمشاريع الأخرى
          plugin_pullrequests: yes
          plugin_pullrequests_sections: created, merged
          plugin_pullrequests_limit: 15
          plugin_pullrequests_draft: no
          
          # plugin للـ Issues المفتوحة في المشاريع الأخرى  
          plugin_issues: yes
          plugin_issues_limit: 15
          
          # Activity في المشاريع الأخرى (مركز ومفيد)
          plugin_activity: yes
          plugin_activity_limit: 8
          plugin_activity_days: 30
          plugin_activity_filter: issue, pr, release, review
          plugin_activity_visibility: public
          
          # تعطيل achievements لتجنب الأخطاء
          plugin_achievements: no
