name: GitHub Metrics — header • activity • followup • languages

on:
  schedule:
    - cron: "0 */6 * * *"   
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: metrics-panels
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1) Header panel
      - name: Metrics — header
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: ${{ github.repository_owner }}
          filename: metrics-header.svg
          base: header
          config_timezone: Asia/Baghdad
          committer_message: "chore(metrics): update header panel"

      # 2) Activity panel
      - name: Metrics — activity
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: ${{ github.repository_owner }}
          filename: metrics-activity.svg
          base: activity
          config_timezone: Asia/Baghdad
          committer_message: "chore(metrics): update activity panel"

      # 3) Follow-up (Issues/PRs created by user)
      - name: Metrics — follow-up (created by me)
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          uses: lowlighter/metrics@v3.34
          filename: metrics-followup.svg
          base: ""                               
          plugin_followup: yes
          plugin_followup_sections: user
          config_timezone: Asia/Baghdad
          committer_message: "chore(metrics): update follow-up panel"

      # 4) Languages (Most used + Recently used)
      - name: Metrics — languages
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: ${{ github.repository_owner }}
          filename: metrics-languages.svg
          base: ""
          plugin_languages: yes
          plugin_languages_sections: most-used, recently-used
          plugin_languages_recent_days: 13
          plugin_languages_recent_load: 300
          config_timezone: Asia/Baghdad
          committer_message: "chore(metrics): update languages panel"
