# .github/workflows/metrics.yml
name: GitHub Metrics
on:
  # يعمل يومياً في منتصف الليل
  schedule: [{cron: "0 0 * * *"}]
  # يمكن تشغيله يدوياً  
  workflow_dispatch:
  # يعمل عند push للـ main branch
  push: {branches: ["master", "main"]}
  
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          # بيانات أساسية
          user: ali90h
          template: classic
          base: header, activity, community, repositories, metadata
          
          # الإعدادات العامة
          config_timezone: Asia/Baghdad
          config_order: base.header, base.activity+community, base.repositories
          
          # إعدادات اللغات مع الألوان والتفاصيل
          plugin_languages: yes
          plugin_languages_sections: most-used, recently-used
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_threshold: 0%
          
          # إحصائيات النشاط المتقدمة
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_visibility: all
          plugin_activity_timestamps: yes
          
          # معلومات المجتمع
          plugin_people: yes
          plugin_people_limit: 24
          plugin_people_size: 28
          plugin_people_types: followers, following
          
          # إحصائيات الـ Issues والـ PRs
          plugin_followup: yes
          plugin_followup_sections: repositories
          plugin_followup_indepth: yes
          
          # خريطة النشاط ثلاثية الأبعاد (مثل Byron!)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          # Achievements والجوائز
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes
          plugin_achievements_display: detailed
          plugin_achievements_limit: 0
          
          # خطوط الكود المكتوبة
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          
          # المشاريع البارزة
          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_repositories: yes
          
          # Traffic وإحصائيات الزوار
          plugin_traffic: yes
          
          # معلومات إضافية مثيرة
          plugin_stargazers: yes
          plugin_stargazers_charts: yes
          plugin_stargazers_charts_type: classic
          
          # إعدادات المظهر النهائية
          config_display: large
          config_animations: yes
          
  # وظيفة منفصلة للـ detailed metrics (مثل الصورة تماماً)
  detailed-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.detailed.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: ali90h
          template: classic
          base: ""
          
          # كل التفاصيل المتقدمة
          config_timezone: Asia/Baghdad
          config_order: languages, followup, people, stargazers, lines, traffic
          config_display: large
          config_animations: yes
          
          # اللغات بشكل مفصل
          plugin_languages: yes
          plugin_languages_sections: most-used, recently-used
          plugin_languages_colors: github
          plugin_languages_limit: 12
          plugin_languages_details: bytes-size, percentage, lines
          plugin_languages_threshold: 1%
          plugin_languages_analysis_timeout: 15
          
          # الخريطة ثلاثية الأبعاد
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          # كل الإحصائيات
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: classic
