name: Metrics
on:
  schedule:
    - cron: "0 6 * * *"   # يشغّل يومياً 06:00 UTC
  workflow_dispatch:       # تشغيل يدوي

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: ali90h
          template: classic
          base: header, activity, community, repositories
          config_timezone: Asia/Baghdad

          # لغات (اختياري)
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_limit: 8
