name: Update README

on:
  schedule:
    - cron: "0 12 * * *"      # كل يوم 12:00 UTC
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: readme-metrics
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update README with recent activity + metrics
    steps:
      - uses: actions/checkout@v4

      # نشاط GitHub (يفترض وجود START/END_SECTION داخل README)
      - name: Update recent activity
        uses: jamesgeorge007/github-activity-readme@master  # مثال لإصدار مبرقَم
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: "chore(readme): update recent activity"
          MAX_LINES: 10

      # توليد metrics.svg
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: ali90h
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Baghdad

          # إضافات اختيارية تعطي شكل أغنى (مثل اللقطة)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_followup: yes
          plugin_followup_sections: repositories, user
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          plugin_languages_limit: 12
          plugin_languages_ignored: html, css
          repositories_affiliations: owner, collaborator, organization_member
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes
